# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('pdf_start', models.IntegerField()),
                ('pdf_end', models.IntegerField()),
                ('is_review', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Memeber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=30)),
                ('current_lesson', models.IntegerField(default=1)),
                ('email', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
