# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-02 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('pdf_start', models.IntegerField()),
                ('pdf_end', models.IntegerField()),
                ('is_review', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('word_id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(help_text='Word', max_length=50)),
                ('translation', models.CharField(help_text='Translation in Target Language', max_length=50)),
                ('word_type', models.CharField(choices=[('N', 'Noun'), ('V', 'Verb'), ('ADJ', 'Adjective'), ('OTR', 'Other')], default='N', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='WordList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name Of List', max_length=50)),
                ('user', models.IntegerField()),
                ('date_created', models.DateField(auto_now=True)),
                ('word_ids', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
    ]
