# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 03:10
from __future__ import unicode_literals

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enlgish', models.CharField(help_text='Word', max_length=50)),
                ('target_lang', models.CharField(help_text='Translation', max_length=50)),
                ('word_type', models.CharField(choices=[('N', 'Noun'), ('V', 'Verb'), ('ADJ', 'Adjective'), ('OTR', 'Other')], default='N', help_text='N for noun, V for verb, ADJ for adjective, and OTHER for other', max_length=3)),
            ],
        ),
    ]
