# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-23 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordlist',
            name='word_ids',
        ),
        migrations.AddField(
            model_name='wordlist',
            name='word_ids',
            field=models.ManyToManyField(to='content.Word'),
        ),
    ]
