# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 03:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20171102_0310'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Memeber',
        ),
    ]
