# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_delete_memeber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='target_lang',
            new_name='translation',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='enlgish',
            new_name='word',
        ),
        migrations.AlterField(
            model_name='word',
            name='word_type',
            field=models.CharField(choices=[('N', 'Noun'), ('V', 'Verb'), ('ADJ', 'Adjective'), ('OTR', 'Other')], default='N', max_length=3),
        ),
    ]
