# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20171102_0329'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='List Name', max_length=50)),
                ('description', models.TextField()),
                ('created_by', models.CharField(help_text='username', max_length=20)),
                ('list_id', models.IntegerField()),
            ],
        ),
    ]
