# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 00:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_wordlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordlist',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wordlist',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
